apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: number-reverser-netpol
  namespace: number-reverser
spec:
  podSelector:
    matchLabels:
      app: number-reverser
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - ports:
        - protocol: TCP
          port: 8000
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
